### ISSUE TITLE
Remove strip() from get_directories()?

### ISSUE THREAD

**Issue by DrNightmare** [ethanphunter/Python-CommandLine#1]
I am not sure why `directoryString` has to be stripped in `get_directories()`.
For instance, if the current working directory contained the following: 
Main.py, .git (a directory) and README.md
and I entered the command 'ls', the output with the current get_directories() function is:

Main.py
DIR .git
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;README.md

As seen above, README.md seems (unnecessarily) shifted to the right. To add a bit of consistency, you could simply not strip `directoryString` before printing it, which would result in the following output:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Main.py
DIR .git
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;README.md

A (probably) prettier way to print it might be to print all directories first, then print all the files, as such:

DIR .git
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Main.py
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;README.md

**Comment by ethanphunter** [comment]
@DrNightmare That's a good point. I literally just started on this last a few days ago and it's a side project so I haven't done a lot to it yet. The reason for the `strip()` in the function `get_directories()` is to remove the end of line char off the end of the list string that would cause an extra line of white space when doing `ls` or `dir`. Thank you for the input I will keep this in mind while working on it.

**Comment by DrNightmare** [comment]
Oh alright. Then you're probably looking for `rstrip()`, it's an inbuilt string method that removes whitespace at the end of a string.
There's also an lstrip() that removes leading whitespace characters.

**Comment by ethanphunter** [comment]
@DrNightmare Cool thanks, I didn't remember that. I think I'm gonna have to use that.
